# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lws.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lws.proto',
  package='lws',
  syntax='proto3',
  serialized_pb=_b('\n\tlws.proto\x12\x03lws\"\x15\n\x06\x46orkID\x12\x0b\n\x03ids\x18\x01 \x03(\t\",\n\x0cGetBlocksArg\x12\x0c\n\x04hash\x18\x01 \x01(\x0c\x12\x0e\n\x06number\x18\x02 \x01(\x05\"\x18\n\x08GetTxArg\x12\x0c\n\x04hash\x18\x01 \x01(\x0c\"\x19\n\tSendTxArg\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\xb5\x03\n\x0bTransaction\x12\x10\n\x08nVersion\x18\x01 \x01(\r\x12\r\n\x05nType\x18\x02 \x01(\r\x12\x12\n\nnLockUntil\x18\x03 \x01(\r\x12\x12\n\nhashAnchor\x18\x04 \x01(\x0c\x12&\n\x06vInput\x18\x05 \x03(\x0b\x32\x16.lws.Transaction.CTxIn\x12\x33\n\x0c\x63\x44\x65stination\x18\x06 \x01(\x0b\x32\x1d.lws.Transaction.CDestination\x12\x0f\n\x07nAmount\x18\x07 \x01(\x03\x12\x0e\n\x06nTxFee\x18\x08 \x01(\x03\x12\x0f\n\x07vchData\x18\t \x01(\x0c\x12\x0e\n\x06vchSig\x18\n \x01(\x0c\x12\x0c\n\x04hash\x18\x0b \x01(\x0c\x12\x0f\n\x07nChange\x18\x0c \x01(\x03\x1a \n\x05\x43TxIn\x12\x0c\n\x04hash\x18\x01 \x01(\x0c\x12\t\n\x01n\x18\x02 \x01(\r\x1a}\n\x0c\x43\x44\x65stination\x12\x0e\n\x06prefix\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0c\n\x04size\x18\x03 \x01(\r\"A\n\x06PREFIX\x12\x0f\n\x0bPREFIX_NULL\x10\x00\x12\x11\n\rPREFIX_PUBKEY\x10\x01\x12\x13\n\x0fPREFIX_TEMPLATE\x10\x02\"\xe4\x01\n\x05\x42lock\x12\x10\n\x08nVersion\x18\x01 \x01(\r\x12\r\n\x05nType\x18\x02 \x01(\r\x12\x12\n\nnTimeStamp\x18\x03 \x01(\r\x12\x10\n\x08hashPrev\x18\x04 \x01(\x0c\x12\x12\n\nhashMerkle\x18\x05 \x01(\x0c\x12\x10\n\x08vchProof\x18\x06 \x01(\x0c\x12 \n\x06txMint\x18\x07 \x01(\x0b\x32\x10.lws.Transaction\x12\x1d\n\x03vtx\x18\x08 \x03(\x0b\x32\x10.lws.Transaction\x12\x0e\n\x06vchSig\x18\t \x01(\x0c\x12\x0f\n\x07nHeight\x18\n \x01(\r\x12\x0c\n\x04hash\x18\x0b \x01(\x0c\"9\n\tSendTxRet\x12\x0c\n\x04hash\x18\x01 \x01(\x0c\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_TRANSACTION_CDESTINATION_PREFIX = _descriptor.EnumDescriptor(
  name='PREFIX',
  full_name='lws.Transaction.CDestination.PREFIX',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PREFIX_NULL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PREFIX_PUBKEY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PREFIX_TEMPLATE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=513,
  serialized_end=578,
)
_sym_db.RegisterEnumDescriptor(_TRANSACTION_CDESTINATION_PREFIX)


_FORKID = _descriptor.Descriptor(
  name='ForkID',
  full_name='lws.ForkID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='lws.ForkID.ids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=39,
)


_GETBLOCKSARG = _descriptor.Descriptor(
  name='GetBlocksArg',
  full_name='lws.GetBlocksArg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='lws.GetBlocksArg.hash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='number', full_name='lws.GetBlocksArg.number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=85,
)


_GETTXARG = _descriptor.Descriptor(
  name='GetTxArg',
  full_name='lws.GetTxArg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='lws.GetTxArg.hash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=111,
)


_SENDTXARG = _descriptor.Descriptor(
  name='SendTxArg',
  full_name='lws.SendTxArg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='lws.SendTxArg.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=138,
)


_TRANSACTION_CTXIN = _descriptor.Descriptor(
  name='CTxIn',
  full_name='lws.Transaction.CTxIn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='lws.Transaction.CTxIn.hash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='n', full_name='lws.Transaction.CTxIn.n', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=419,
  serialized_end=451,
)

_TRANSACTION_CDESTINATION = _descriptor.Descriptor(
  name='CDestination',
  full_name='lws.Transaction.CDestination',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prefix', full_name='lws.Transaction.CDestination.prefix', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='lws.Transaction.CDestination.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='lws.Transaction.CDestination.size', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TRANSACTION_CDESTINATION_PREFIX,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=453,
  serialized_end=578,
)

_TRANSACTION = _descriptor.Descriptor(
  name='Transaction',
  full_name='lws.Transaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nVersion', full_name='lws.Transaction.nVersion', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nType', full_name='lws.Transaction.nType', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nLockUntil', full_name='lws.Transaction.nLockUntil', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hashAnchor', full_name='lws.Transaction.hashAnchor', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vInput', full_name='lws.Transaction.vInput', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cDestination', full_name='lws.Transaction.cDestination', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nAmount', full_name='lws.Transaction.nAmount', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nTxFee', full_name='lws.Transaction.nTxFee', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vchData', full_name='lws.Transaction.vchData', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vchSig', full_name='lws.Transaction.vchSig', index=9,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hash', full_name='lws.Transaction.hash', index=10,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nChange', full_name='lws.Transaction.nChange', index=11,
      number=12, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TRANSACTION_CTXIN, _TRANSACTION_CDESTINATION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=578,
)


_BLOCK = _descriptor.Descriptor(
  name='Block',
  full_name='lws.Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nVersion', full_name='lws.Block.nVersion', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nType', full_name='lws.Block.nType', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nTimeStamp', full_name='lws.Block.nTimeStamp', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hashPrev', full_name='lws.Block.hashPrev', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hashMerkle', full_name='lws.Block.hashMerkle', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vchProof', full_name='lws.Block.vchProof', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='txMint', full_name='lws.Block.txMint', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vtx', full_name='lws.Block.vtx', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vchSig', full_name='lws.Block.vchSig', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nHeight', full_name='lws.Block.nHeight', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hash', full_name='lws.Block.hash', index=10,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=581,
  serialized_end=809,
)


_SENDTXRET = _descriptor.Descriptor(
  name='SendTxRet',
  full_name='lws.SendTxRet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='lws.SendTxRet.hash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='lws.SendTxRet.result', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reason', full_name='lws.SendTxRet.reason', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=811,
  serialized_end=868,
)

_TRANSACTION_CTXIN.containing_type = _TRANSACTION
_TRANSACTION_CDESTINATION.containing_type = _TRANSACTION
_TRANSACTION_CDESTINATION_PREFIX.containing_type = _TRANSACTION_CDESTINATION
_TRANSACTION.fields_by_name['vInput'].message_type = _TRANSACTION_CTXIN
_TRANSACTION.fields_by_name['cDestination'].message_type = _TRANSACTION_CDESTINATION
_BLOCK.fields_by_name['txMint'].message_type = _TRANSACTION
_BLOCK.fields_by_name['vtx'].message_type = _TRANSACTION
DESCRIPTOR.message_types_by_name['ForkID'] = _FORKID
DESCRIPTOR.message_types_by_name['GetBlocksArg'] = _GETBLOCKSARG
DESCRIPTOR.message_types_by_name['GetTxArg'] = _GETTXARG
DESCRIPTOR.message_types_by_name['SendTxArg'] = _SENDTXARG
DESCRIPTOR.message_types_by_name['Transaction'] = _TRANSACTION
DESCRIPTOR.message_types_by_name['Block'] = _BLOCK
DESCRIPTOR.message_types_by_name['SendTxRet'] = _SENDTXRET

ForkID = _reflection.GeneratedProtocolMessageType('ForkID', (_message.Message,), dict(
  DESCRIPTOR = _FORKID,
  __module__ = 'lws_pb2'
  # @@protoc_insertion_point(class_scope:lws.ForkID)
  ))
_sym_db.RegisterMessage(ForkID)

GetBlocksArg = _reflection.GeneratedProtocolMessageType('GetBlocksArg', (_message.Message,), dict(
  DESCRIPTOR = _GETBLOCKSARG,
  __module__ = 'lws_pb2'
  # @@protoc_insertion_point(class_scope:lws.GetBlocksArg)
  ))
_sym_db.RegisterMessage(GetBlocksArg)

GetTxArg = _reflection.GeneratedProtocolMessageType('GetTxArg', (_message.Message,), dict(
  DESCRIPTOR = _GETTXARG,
  __module__ = 'lws_pb2'
  # @@protoc_insertion_point(class_scope:lws.GetTxArg)
  ))
_sym_db.RegisterMessage(GetTxArg)

SendTxArg = _reflection.GeneratedProtocolMessageType('SendTxArg', (_message.Message,), dict(
  DESCRIPTOR = _SENDTXARG,
  __module__ = 'lws_pb2'
  # @@protoc_insertion_point(class_scope:lws.SendTxArg)
  ))
_sym_db.RegisterMessage(SendTxArg)

Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), dict(

  CTxIn = _reflection.GeneratedProtocolMessageType('CTxIn', (_message.Message,), dict(
    DESCRIPTOR = _TRANSACTION_CTXIN,
    __module__ = 'lws_pb2'
    # @@protoc_insertion_point(class_scope:lws.Transaction.CTxIn)
    ))
  ,

  CDestination = _reflection.GeneratedProtocolMessageType('CDestination', (_message.Message,), dict(
    DESCRIPTOR = _TRANSACTION_CDESTINATION,
    __module__ = 'lws_pb2'
    # @@protoc_insertion_point(class_scope:lws.Transaction.CDestination)
    ))
  ,
  DESCRIPTOR = _TRANSACTION,
  __module__ = 'lws_pb2'
  # @@protoc_insertion_point(class_scope:lws.Transaction)
  ))
_sym_db.RegisterMessage(Transaction)
_sym_db.RegisterMessage(Transaction.CTxIn)
_sym_db.RegisterMessage(Transaction.CDestination)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), dict(
  DESCRIPTOR = _BLOCK,
  __module__ = 'lws_pb2'
  # @@protoc_insertion_point(class_scope:lws.Block)
  ))
_sym_db.RegisterMessage(Block)

SendTxRet = _reflection.GeneratedProtocolMessageType('SendTxRet', (_message.Message,), dict(
  DESCRIPTOR = _SENDTXRET,
  __module__ = 'lws_pb2'
  # @@protoc_insertion_point(class_scope:lws.SendTxRet)
  ))
_sym_db.RegisterMessage(SendTxRet)


# @@protoc_insertion_point(module_scope)
